// angular/src/app/components/trend-chart/trend-chart.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Store } from '@ngrx/store';
import { Subject, combineLatest } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import { CommonModule } from '@angular/common';
import { BaseChartDirective } from 'ng2-charts';
import { ChartConfiguration, ChartOptions } from 'chart.js';
import { AppState } from '../../store/app.state';
import { KPIs } from '../../models/product.model';

interface TrendData {
  date: string;
  stock: number;
  demand: number;
}

@Component({
  selector: 'app-trend-chart',
  imports: [CommonModule, BaseChartDirective],
  templateUrl: './trend-chart.html',
  styleUrl: './trend-chart.css'
})
export class TrendChart implements OnInit, OnDestroy {
  private destroy$ = new Subject<void>();

  public lineChartData: ChartConfiguration<'line'>['data'] = {
    labels: [],
    datasets: [
      {
        data: [],
        label: 'Stock',
        fill: false,
        tension: 0.3,
        borderColor: '#3b82f6',
        backgroundColor: '#3b82f6',
        pointBackgroundColor: '#3b82f6',
        pointBorderColor: '#3b82f6',
        pointRadius: 3,
        pointHoverRadius: 4,
        borderWidth: 2
      },
      {
        data: [],
        label: 'Demand',
        fill: false,
        tension: 0.3,
        borderColor: '#10b981',
        backgroundColor: '#10b981',
        pointBackgroundColor: '#10b981',
        pointBorderColor: '#10b981',
        pointRadius: 3,
        pointHoverRadius: 4,
        borderWidth: 2
      }
    ]
  };

  public lineChartOptions: ChartOptions<'line'> = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: true,
        position: 'bottom',
        labels: {
          usePointStyle: true,
          padding: 20,
          font: {
            size: 12
          }
        }
      },
      tooltip: {
        backgroundColor: '#fff',
        titleColor: '#374151',
        bodyColor: '#374151',
        borderColor: '#e5e7eb',
        borderWidth: 1,
        cornerRadius: 6,
        displayColors: true,
        callbacks: {
          label: (context) => {
            const value = Math.round(context.parsed.y).toLocaleString();
            return `${context.dataset.label}: ${value}`;
          }
        }
      }
    },
    scales: {
      y: {
        display: true,
        grid: {
          color: '#f0f0f0'
        },
        ticks: {
          color: '#6b7280',
          font: {
            size: 12
          },
          callback: function(value) {
            return Number(value).toLocaleString();
          }
        },
        border: {
          display: false
        }
      },
      x: {
        display: true,
        grid: {
          color: '#f0f0f0'
        },
        ticks: {
          color: '#6b7280',
          font: {
            size: 12
          }
        },
        border: {
          display: false
        }
      }
    }
  };

  public lineChartType = 'line' as const;

  constructor(private store: Store<AppState>) {}

  ngOnInit(): void {
    // Subscribe to dateRange and KPIs changes
    combineLatest([
      this.store.select(state => state.ui.dateRange),
      this.store.select(state => state.products.kpis)
    ]).pipe(
      takeUntil(this.destroy$)
    ).subscribe(([dateRange, kpis]) => {
      console.log(`Chart component received state update: dateRange=${dateRange}, totalStock=${kpis.totalStock}`);
      this.updateChartData(dateRange, kpis);
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  private updateChartData(dateRange: '7d' | '14d' | '30d', kpis: KPIs): void {
    const days = dateRange === '7d' ? 7 : dateRange === '14d' ? 14 : 30;
    const trendData = this.generateTrendData(days, kpis);

    // Create new data object to trigger change detection
    this.lineChartData = {
      labels: trendData.map(item => item.date),
      datasets: [
        {
          ...this.lineChartData.datasets[0],
          data: trendData.map(item => item.stock)
        },
        {
          ...this.lineChartData.datasets[1],
          data: trendData.map(item => item.demand)
        }
      ]
    };
    
    console.log(`Updated chart for ${days} days with ${trendData.length} data points`);
  }

  private generateTrendData(days: number, kpis: KPIs): TrendData[] {
    const data: TrendData[] = [];
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(endDate.getDate() - days + 1);

    for (let i = 0; i < days; i++) {
      const date = new Date(startDate);
      date.setDate(date.getDate() + i);
      
      const isToday = i === days - 1;
      const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                         'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
      
      data.push({
        date: `${monthNames[date.getMonth()]} ${date.getDate()}`,
        // For historical days, use simulated data around current totals
        // For today, use actual current totals
        stock: isToday ? kpis.totalStock : kpis.totalStock + Math.random() * 40 - 20,
        demand: isToday ? kpis.totalDemand : kpis.totalDemand + Math.random() * 30 - 15
      });
    }

    return data;
  }
}

// src/components/TrendChart.tsx
import React, { useMemo } from 'react';
import { useSelector } from 'react-redux';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, ResponsiveContainer, Legend, Tooltip } from 'recharts';
import { RootState } from '../store';
import { TrendData } from '../types';

const TrendChart: React.FC = () => {
  const dateRange = useSelector((state: RootState) => state.ui.dateRange);
  const { kpis } = useSelector((state: RootState) => state.products);
  
  const days = dateRange === '7d' ? 7 : dateRange === '14d' ? 14 : 30;
  
  // Generate trend data with today's date and current totals
  const data = useMemo(() => {
    const trendData: TrendData[] = [];
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(endDate.getDate() - days + 1);

    for (let i = 0; i < days; i++) {
      const date = new Date(startDate);
      date.setDate(date.getDate() + i);
      
      const isToday = i === days - 1;
      const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                         'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
      
      trendData.push({
        date: `${monthNames[date.getMonth()]} ${date.getDate()}`,
        // For historical days, use simulated data around current totals
        // For today, use actual current totals
        stock: isToday ? kpis.totalStock : kpis.totalStock + Math.random() * 40 - 20,
        demand: isToday ? kpis.totalDemand : kpis.totalDemand + Math.random() * 30 - 15
      });
    }

    return trendData;
  }, [days, kpis.totalStock, kpis.totalDemand]);

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-6 mb-8 shadow-sm">
      <h3 className="text-lg font-semibold text-gray-900 mb-6">Stock vs Demand Trend</h3>
      
      <div className="h-80">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={data} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
            <XAxis 
              dataKey="date" 
              axisLine={false}
              tickLine={false}
              tick={{ fontSize: 12, fill: '#6b7280' }}
            />
            <YAxis 
              axisLine={false}
              tickLine={false}
              tick={{ fontSize: 12, fill: '#6b7280' }}
              domain={['dataMin - 50', 'dataMax + 50']}
            />
            <Tooltip 
              contentStyle={{ 
                backgroundColor: '#fff', 
                border: '1px solid #e5e7eb',
                borderRadius: '6px',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'
              }}
              labelStyle={{ color: '#374151', fontWeight: '500' }}
              formatter={(value: number, name: string) => [Math.round(value).toLocaleString(), name]}
            />
            <Legend 
              wrapperStyle={{ paddingTop: '20px' }}
              iconType="line"
            />
            <Line
              type="monotone"
              dataKey="stock"
              stroke="#3b82f6"
              strokeWidth={2}
              dot={{ fill: '#3b82f6', strokeWidth: 2, r: 3 }}
              name="Stock"
            />
            <Line
              type="monotone"
              dataKey="demand"
              stroke="#10b981"
              strokeWidth={2}
              dot={{ fill: '#10b981', strokeWidth: 2, r: 3 }}
              name="Demand"
            />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
};

export default TrendChart;
